#!/bin/bash
#
# Distributed under the terms of GNU GPL version 2
#
# Origninal author:
# http://marius.scurtescu.com/?p=102
#
#
# modified 07/27/2011 :
#   - corrected awk script
# modified 09/25/2010 :
# 	- added the pipe to see what appens in real time + some text
#	- awk tweak to get a proper list
#
# author: remi.flamary at gmail.com


( #echo "Info $@:"
    svn status "$@"
   # echo "Done."
    ) | awk '/A |M |\? / { print $1; print $2  }'| zenity --list --column "Status" --column "File" --title="Subversion: Info" --width=600 --height=400 --window-icon="`dirname $0`/svn.xpm"

