#!/bin/bash
#
# Distributed under the terms of GNU GPL version 2
#
# Origninal author:
# http://marius.scurtescu.com/?p=102
#
#
# modified 09/25/2010 :
# 	- added the pipe to see what appens in real time + some text
# modified 10/07/2010 :
#	- added non-interactive for conflict case
#
# author: remi.flamary at gmail.com


( echo "Updating $@"
    svn update "$@" --non-interactive 2>&1 
    echo "Done."
    ) | zenity --text-info --title="Subversion: Update" --width=600 --height=400 --window-icon="`dirname $0`/svn.xpm"

