#!/bin/bash
#
# Distributed under the terms of GNU GPL version 2
#
# Origninal author:
# http://marius.scurtescu.com/?p=102
#
#
# modified 09/25/2010 :
# 	- added the pipe to see what appens in real time + some text
#
# author: remi.flamary at gmail.com


ICONPATH="`dirname $0`/svn.xpm"

URL=`zenity --entry --title="Subversion: Checkout" --text="Enter repository URL:" --entry-text="svn://" --width=400 --window-icon="$ICONPATH" 2>&1`

if [ $? -eq 0 ] ; then
(
 echo "Checkout:"   
svn checkout $URL
echo "done") | zenity --text-info --title="Subversion: Checkout" --width=600 --height=400 --window-icon="$ICONPATH"

fi
