#!/bin/bash
#
# Distributed under the terms of GNU GPL version 2
#
# Origninal author:
# http://marius.scurtescu.com/?p=102
#
#
# modified 09/25/2010 :
# 	- added the pipe to see what appens in real time + some text
#
# author: remi.flamary at gmail.com



if [ -z $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ] ; then
    svn revert . | zenity --text-info --title="Subversion: Revert" --width=600 --height=400 --window-icon="`dirname $0`/svn.xpm"
else
    svn revert "$@" | zenity --text-info --title="Subversion: Revert" --width=600 --height=400 --window-icon="`dirname $0`/svn.xpm"
fi


